services:
  web:
    build: .
    command: sh set_up.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        # replace with your own desired credentials
        - POSTGRES_USER=oli98
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
volumes:
  postgres_data: